- name: Add Cilium Helm repo
  kubernetes.core.helm_repository:
    name: cilium
    repo_url: https://helm.cilium.io/

- name: Install Cilium from Helm chart
  environment:
    HELM_DIFF_USE_INSECURE_SERVER_SIDE_DRY_RUN: "true"
  kubernetes.core.helm:
    name: cilium
    chart_ref: cilium/cilium
    chart_version: 1.16.5
    release_namespace: kube-system
    values: "{{ lookup('file', 'cilium/values.yaml') | from_yaml }}"
    wait: true

- name: Add cluster-wide network policy to allow healthchecks
  kubernetes.core.k8s:
    definition: "{{ lookup('file', 'cilium/clusterwide-network-policy-node-healthcheck.yaml') |from_yaml }}"

- name: Add network policy to allow namespace traffic
  kubernetes.core.k8s:
    definition: "{{ lookup('file', 'cilium/network-policy-namespace.yaml') |from_yaml }}"
