- name: Add Cilium Helm repo
  kubernetes.core.helm_repository:
    name: cilium
    repo_url: https://helm.cilium.io/

- name: Install Cilium from Helm chart
  kubernetes.core.helm:
    name: cilium
    chart_ref: cilium/cilium
    chart_version: 1.16.5
    release_namespace: kube-system
    values: "{{ lookup('file', 'cilium/values.yaml') | from_yaml }}"
    wait: true
