- name: Prepare variables & directories
  ansible.builtin.include_tasks: setup.yml

- name: Ensure talosctl is available
  ansible.builtin.include_tasks: talosctl.yml

- name: Include tasks to prepare talos config file
  ansible.builtin.include_tasks: talos_prepare_config.yml

- name: Include tasks to apply talos config
  ansible.builtin.include_tasks: talos_apply_config.yml

- name: Include tasks to bootstrap etcd & setup kubernetes cluster
  ansible.builtin.include_tasks: kubernetes_bootstrap.yml
  when: talos_is_bootstrap

- name: Include tasks to prepare kubeconfig file
  ansible.builtin.include_tasks: kubernetes_kubeconfig.yml
  when: talos_is_bootstrap

- name: Include tasks to install Cilium
  ansible.builtin.include_tasks: cilium.yml
  run_once: true
