- name: Get kubeconfig to start interacting with Kubernetes
  ansible.builtin.command:
    chdir: "{{ talos_tmp_root.path }}"
    cmd: >
      ./talosctl
      --talosconfig talosconfig
      kubeconfig .
  changed_when: false

- name: Set up Kubernetes
  environment: "{{ kubernetes_env_vars }}"
  block:
    - name: Wait for cluster to be ready
      kubernetes.core.k8s_cluster_info:
      retries: 12
      delay: 10
