- name: Get kubeconfig to start interacting with Kubernetes
  ansible.builtin.command:
    chdir: "{{ talos_tmp_root.path }}"
    # Hardcode a controller as the node target (hence talos_endpoint_ips) as
    # this will always be a valid target. Useful when running this playbook from
    # other nodes to generate a kubeconfig. ansible_host would not contain the
    # right IP address.
    cmd: >
      ./talosctl
      --talosconfig talosconfig
      --nodes "{{ talos_endpoint_ips[0] }}"
      kubeconfig .
  changed_when: false

- name: Set up Kubernetes
  environment: "{{ kubernetes_env_vars }}"
  block:
    - name: Wait for cluster to be ready
      kubernetes.core.k8s_cluster_info:
      retries: 12
      delay: 10
