- name: Prepare variables & directories
  ansible.builtin.include_tasks: setup.yml

- name: Ensure talosctl is available
  ansible.builtin.include_tasks: talosctl.yml

- name: Include tasks to create secrets file
  ansible.builtin.include_tasks: talos_write_secrets.yml

- name: Include tasks to create talosconfig
  ansible.builtin.include_tasks: talosconfig.yml

- name: Include tasks to prepare kubeconfig file
  ansible.builtin.include_tasks: kubernetes_kubeconfig.yml
