- name: Install talosctl from github
  run_once: true
  install_from_github:
    repo: siderolabs/talos
    tag: "{{ talos_ctl_version }}"
    version_command: "{{ talos_tmp_root.path }}/talosctl version --client --short"
    asset_regex: ^talosctl-linux-amd64$
    move_rules:
      - src_regex: ^talosctl-linux-amd64$
        dst: "{{ talos_tmp_root.path }}/talosctl"
        mode: "0755"
