- name: Generate talosconfig from secrets file
  changed_when: false
  when: talos_is_bootstrap
  ansible.builtin.command:
    chdir: "{{ talos_tmp_path.path }}"
    cmd: >
      {{ talos_tmp_root.path }}/talosctl
      gen
      config
      --with-secrets {{ talos_tmp_root.path }}/secrets.prod.yaml
      --config-patch-control-plane @config.patch.yaml
      --output-types talosconfig
      --output {{ talos_tmp_root.path }}/talosconfig
      --install-image  factory.talos.dev/installer/{{ talos_image_id }}:v{{ talos_image_version }}
      --talos-version {{ talos_image_version }}
      --kubernetes-version {{ talos_kubernetes_version }}
      --force
      {{ talos_cluster_name }}
      https://{{ ansible_host }}:6443

- name: Determine endpoint & node IPs
  ansible.builtin.set_fact:
    talos_node_ips: "{{ groups['k8s'] | map('extract', hostvars, 'ansible_host') }}"
    talos_endpoint_ips: "{{ groups['controller'] | map('extract', hostvars, 'ansible_host') }}"

- name: Update talosconfig with endpoint IPs
  changed_when: false
  ansible.builtin.command:
    chdir: "{{ talos_tmp_root.path }}"
    cmd: >
      {{ talos_tmp_root.path }}/talosctl
      --talosconfig talosconfig
      config
      endpoint
      {{ talos_endpoint_ips | join(' ') }}

- name: Update talosconfig with node IPs
  changed_when: false
  ansible.builtin.command:
    chdir: "{{ talos_tmp_root.path }}"
    cmd: >
      {{ talos_tmp_root.path }}/talosctl
      --talosconfig talosconfig
      config
      node
      {{ talos_node_ips | join(' ') }}
