- name: Include tasks for create secrets file
  ansible.builtin.include_tasks: talos_write_secrets.yml

- name: Include tasks for talosconfig file
  ansible.builtin.include_tasks: talosconfig.yml
  run_once: true

- name: Include tasks for control plane config
  ansible.builtin.include_tasks: talos_prepare_controlplane.yml
  when: talos_is_controller

- name: Include tasks for worker config
  ansible.builtin.include_tasks: talos_prepare_worker.yml
  when: not talos_is_controller
