- name: Write secrets to file
  ansible.builtin.copy:
    src: "{{ talos_secrets_file }}"
    dest: "{{ talos_tmp_path.path }}/secrets.prod.yaml"
    mode: "0600"
  no_log: true

- name: Copy config patch
  ansible.builtin.template:
    src: config.patch.yaml.j2
    dest: "{{ talos_tmp_path.path }}/config.patch.yaml"

- name: Generate config from secrets file
  ansible.builtin.command:
    chdir: "{{ talos_tmp_path.path }}"
    cmd: >
      ./talosctl
      gen
      config
      --with-secrets secrets.prod.yaml
      --config-patch-control-plane @config.patch.yaml
      --output .
      --install-image  factory.talos.dev/installer/{{ talos_image_id }}:v{{ talos_image_version }}
      --talos-version {{ talos_image_version }}
      --kubernetes-version {{ talos_kubernetes_version }}
      --force
      {{ talos_cluster_name }}
      https://{{ ansible_host }}:6443
  changed_when: false

- name: Validate config
  ansible.builtin.command:
    chdir: "{{ talos_tmp_path.path }}"
    cmd: >
      ./talosctl
      --config controlplane.yaml
      validate
      --mode metal
  changed_when: false

- name: Update talosconfig with node details
  ansible.builtin.command:
    chdir: "{{ talos_tmp_path.path }}"
    cmd: >
      ./talosctl
      --talosconfig talosconfig
      config
      {{ item }}
      {{ ansible_host }}
  loop:
    - endpoint
    - node
  changed_when: false
