- name: Generate talosconfig from secrets file
  changed_when: false
  ansible.builtin.command:
    chdir: "{{ talos_tmp_root.path }}"
    cmd: >
      ./talosctl
      gen
      config
      --with-secrets secrets.prod.yaml
      --output-types talosconfig
      --output talosconfig
      --force
      {{ talos_cluster_name }}
      https://{{ talos_controlplane_ip }}:6443

- name: Update talosconfig with endpoint IPs
  changed_when: false
  ansible.builtin.command:
    chdir: "{{ talos_tmp_root.path }}"
    cmd: >
      {{ talos_tmp_root.path }}/talosctl
      --talosconfig talosconfig
      config
      endpoint
      {{ talos_endpoint_ips | join(' ') }}

- name: Update talosconfig with node IPs
  changed_when: false
  ansible.builtin.command:
    chdir: "{{ talos_tmp_root.path }}"
    cmd: >
      {{ talos_tmp_root.path }}/talosctl
      --talosconfig talosconfig
      config
      node
      {{ talos_node_ips | join(' ') }}
