- name: Write secrets to file
  no_log: true
  run_once: true
  ansible.builtin.copy:
    src: "{{ talos_secrets_file }}"
    dest: "{{ talos_tmp_root.path }}/secrets.prod.yaml"
    mode: "0600"

- name: Include tasks for talosconfig file
  ansible.builtin.include_tasks: talosconfig.yml
  when: talos_is_bootstrap

- name: Include tasks for control plane config
  ansible.builtin.include_tasks: talos_prepare_controlplane.yml
  when: talos_is_controller

- name: Include tasks for worker config
  ansible.builtin.include_tasks: talos_prepare_worker.yml
  when: not talos_is_controller
