- name: Add Longhorn Helm repo
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: https://charts.longhorn.io

- name: Create namespace
  kubernetes.core.k8s:
    definition: "{{ lookup('file', 'namespace.yaml') | from_yaml }}"

- name: Add network policy
  kubernetes.core.k8s:
    definition: "{{ lookup('file', 'network-policy-namespace.yaml') | from_yaml }}"

- name: Add cluster wide network policy
  kubernetes.core.k8s:
    definition: "{{ lookup('file', 'clusterwide-network-policy-healthcheck.yaml') | from_yaml }}"

- name: Install Longhorn from Helm chart
  kubernetes.core.helm:
    name: longhorn
    chart_ref: longhorn/longhorn
    release_namespace: longhorn-system
    values: "{{ lookup('file', 'values.yaml') | from_yaml }}"
