- name: Add MetalLB Helm repo
  kubernetes.core.helm_repository:
    name: metallb
    repo_url: https://metallb.github.io/metallb

- name: Create namespace
  kubernetes.core.k8s:
    definition: "{{ lookup('file', 'namespace.yaml') | from_yaml }}"

- name: Install MetalLB from Helm chart
  kubernetes.core.helm:
    name: metallb
    chart_ref: metallb/metallb
    release_namespace: metallb-system

- name: Create IPAddressPool
  kubernetes.core.k8s:
    template: ipaddresspool.yaml.j2
  # Takes some time to create the CRDs, so retry
  retries: 5
  delay: 3

- name: Create L2Advertisement
  kubernetes.core.k8s:
    definition: "{{ lookup('file', 'l2advertisement.yaml') | from_yaml }}"
