- name: Add CoreDNS Helm repo
  kubernetes.core.helm_repository:
    name: coredns
    repo_url: https://coredns.github.io/helm

- name: Install CoreDNS from Helm chart
  kubernetes.core.helm:
    name: coredns
    chart_ref: coredns/coredns
    release_namespace: kube-system
    create_namespace: true
    values: "{{ lookup('template', 'values.yaml.j2') | from_yaml }}"
