- name: Create VM on Proxmox
  loop: "{{ talos_host_vms }}"
  community.general.proxmox_kvm:
    node: "{{ item.node }}"
    api_user: "{{ talos_host_proxmox_user }}"
    api_token_id: "{{ talos_host_proxmox_token_id }}"
    api_token_secret: "{{ talos_host_proxmox_token_secret }}"
    api_host: "{{ talos_host_proxmox_host }}"
    vmid: "{{ item.vm_id }}"
    name: "{{ item.name }}"
    agent: true  # Use QEMU guest agent
    memory: 4096
    cpu: "{{ talos_host_vm_cpu }}"
    ostype: l26  # Linux 2.6 kernel
    cores: 2
    onboot: true  # Start on PVE boot
    ide:
      ide0: "local:iso/talos-metal-amd64.iso,media=cdrom"
    scsi:
      scsi0: "local-zfs:20,iothread=1,discard=on"
      scsi1: "local-zfs:100,iothread=1,discard=on"
    scsihw: virtio-scsi-single
    net:
      net0: virtio,bridge=vmbr0
    state: present
    # Talos doesn't support ballooning
    balloon: 0
    # TODO: Make tags dynamic based on node role
    tags: "{{ item.tags }}"

- name: Start the VM
  loop: "{{ talos_host_vms }}"
  community.general.proxmox_kvm:
    api_user: "{{ talos_host_proxmox_user }}"
    api_token_id: "{{ talos_host_proxmox_token_id }}"
    api_token_secret: "{{ talos_host_proxmox_token_secret }}"
    api_host: "{{ talos_host_proxmox_host }}"
    vmid: "{{ item.vm_id }}"
    state: started

- name: Include tasks to validate VM name
  loop: "{{ talos_host_vms }}"
  ansible.builtin.include_tasks: wait_vm.yml

- name: Trigger inventory refresh
  ansible.builtin.meta: refresh_inventory
