- name: Create VM on Proxmox
  loop: "{{ talos_host_vms }}"
  community.general.proxmox_kvm:
    node: "{{ item.node }}"
    api_user: "{{ talos_host_proxmox_user }}"
    api_token_id: "{{ talos_host_proxmox_token_id }}"
    api_token_secret: "{{ talos_host_proxmox_token_secret }}"
    api_host: "{{ talos_host_proxmox_host }}"
    vmid: "{{ item.vm_id }}"
    name: "{{ item.name }}"
    agent: true  # Use QEMU guest agent
    memory: "{{ item.memory }}"
    cpu: "{{ talos_host_vm_cpu }}"
    ostype: l26  # Linux 2.6 kernel
    cores: 4
    onboot: true  # Start on PVE boot
    ide:
      ide0: "local:iso/talos-metal-amd64.iso,media=cdrom"
    scsihw: virtio-scsi-single
    net:
      net0: virtio,bridge=vmbr0
    state: present
    # Talos doesn't support ballooning
    balloon: 0
    # TODO: Make tags dynamic based on node role
    tags: "{{ item.tags }}"

- name: Add second nic private VLAN network
  loop: "{{ talos_host_vms }}"
  community.general.proxmox_nic:
    api_user: "{{ talos_host_proxmox_user }}"
    api_token_id: "{{ talos_host_proxmox_token_id }}"
    api_token_secret: "{{ talos_host_proxmox_token_secret }}"
    api_host: "{{ talos_host_proxmox_host }}"
    vmid: "{{ item.vm_id }}"
    interface: net1
    bridge: vmbr0
    tag: "{{ item.vlan_tag }}"
  when: item.vlan_tag

- name: Include tasks for disks
  ansible.builtin.include_tasks: disks.yml
  loop: "{{ talos_host_vms }}"
  loop_control:
    loop_var: vm

- name: Start the VM
  loop: "{{ talos_host_vms }}"
  community.general.proxmox_kvm:
    api_user: "{{ talos_host_proxmox_user }}"
    api_token_id: "{{ talos_host_proxmox_token_id }}"
    api_token_secret: "{{ talos_host_proxmox_token_secret }}"
    api_host: "{{ talos_host_proxmox_host }}"
    vmid: "{{ item.vm_id }}"
    state: started

- name: Include tasks to validate VM name
  loop: "{{ talos_host_vms }}"
  ansible.builtin.include_tasks: wait_vm.yml

- name: Trigger inventory refresh
  ansible.builtin.meta: refresh_inventory
