- name: Prepare variables for VMs of type {{ node_type }}
  block:
    - name: Set facts to be added to list
      ansible.builtin.set_fact:
        vm_cfg:
          vm_id: "{{ item.vm_id }}"
          # For example talos-prod-worker-1 or talos-prod-controller-1
          name: "{{ talos_host_vm_name_prefix }}-{{ node_type }}-{{ idx + 1 }}"
          node: "{{ item.proxmox_node }}"
          tags: "{{ ['k8s', 'prod', node_type] + ['bootstrap'] if idx == 0 and node_type == 'controller' else [] }}"

    - name: Append to list
      ansible.builtin.set_fact:
        talos_host_vms: "{{ talos_host_vms | default([]) + [vm_cfg] }}"
